/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenAccountRouteImport } from './routes/open-account'
import { Route as IndexRouteImport } from './routes/index'

const OpenAccountRoute = OpenAccountRouteImport.update({
  id: '/open-account',
  path: '/open-account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/open-account': typeof OpenAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/open-account': typeof OpenAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/open-account': typeof OpenAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/open-account'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/open-account'
  id: '__root__' | '/' | '/open-account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpenAccountRoute: typeof OpenAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/open-account': {
      id: '/open-account'
      path: '/open-account'
      fullPath: '/open-account'
      preLoaderRoute: typeof OpenAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpenAccountRoute: OpenAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
